### PR TITLE
boblight support working & native compile support

### PR DESCRIPTION
**Pull request by Stasik0**
Hi gimli,

the boblight support is finally ready. I have also add the dependency on libboblight and a native compilation script.

The makefiles have been tested in a native environment, but not on a cross-compile machine. Please take a moment to look into the configure part of Makefile.boblight.

The compiled source can be found here: http://www.vzoltan.com/stasiko/omxplayer-dist.tar.gz

Greetz

### CODE REVIEW

**Comment by Memphiz** [comment]
You definitly need to squash these commits down and get rid of the intermediate states. (see git rebase HEAD~24 -i). I guess nobody will review this mess ;).

But i'm all happy that you got something working and am willing to do a review of the code once you have squashed it down to 1 - 4 logical commits.

Beside that @huceke we have libboblight in the darwin deps for doing crosscompilation as needed - maybe this could be usefull for rbpi too:

https://github.com/xbmc/xbmc/blob/master/tools/darwin/depends/libboblight/Makefile

I also added it to the buildroot of pivos:

https://github.com/Pivosgroup/buildroot-linux/tree/master/package/thirdparty/boblight

**Comment by Memphiz** [comment]
Mhhh reading a bit in the code - what i don't like in that approach is that its totally bound to rbpi and is going completly beside that boblight addon. It would be much cooler if you could hook that solution into our CRenderCapture interface somehow so that boblight addon can be used as with all other platforms. Well thats just my 2 cents - i'm looking forward to hucekes comments on that.

**Comment by Stasik0** [comment]
Regarding the temporary commits - what is the best strategy for doing it? just squashing them all to one pull request? I think it is all done for one feature.

Regarding the boblight addon, I _did_ edit only the standalone version yet. I thought of reading the boblight server parameter from the boblight addon in XBMC for the embedded version (currently they are passed via command line). The bounding to rbpi and linux is imho unavoidable, since i have to use the custom broadcom's OMX components to achieve the capturing goal (i need to plug myself into the rendering pipeline).

Regarding the CRenderCapture interface, i need a bit more information on XMBC structure. At the moment, I do not really have a clue how omxplayer is embedded in XMBC (since I did only dig into the standalone version). Could we hook up in IRC or gtalk?

**Comment by Memphiz** [comment]
I didn't even realise that this pr is about the standalone player. I'm not the right person to talk to when it comes to rbpi internals + xbmc - huceke would be the right person to talk to in that manner. (i'm only maintaining the boblight addon ;) ).

**Comment by Stasik0** [comment]
oh no, rebasing is a hell! hopefully i did not mess everything up... i will try to talk to someone from xbmc-dev about the CRenderCaptrue

**Comment by huceke** [comment]
Smash it down to one commit please.

**Comment by Stasik0** [comment]
i will open a new one

**Comment by Memphiz** [comment]
for the next time:

http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

after that force push to your repo and it will update the pullrequest automagically...

**Comment by Stasik0** [comment]
i had many problems with that since i had some merges pulled up from the upstream :)

does not really matter... can we hook up together to discuss some of the CRenderCapture business?

**Comment by Memphiz** [comment]
For the rendercapture you should talk to bobo1on1 on #xbmc-dev or #xbmc (if he is there - no clue) - i'm still at work for the next couple of hours ...

**Comment by Stasik0** [comment]
Okay, no stress, we can talk in the evening or on we...

Am 18.01.2013 um 16:12 schrieb Memphiz notifications@github.com:

For the rendercapture you should talk to bobo1on1 on #xbmc-dev or #xbmc (if
he is there - no clue) - i'm still at work for the next couple of hours ...

—
Reply to this email directly or view it on
GitHubhttps://github.com/huceke/omxplayer/pull/97#issuecomment-12425831.

**Pull request closed without merging**
