### PR TITLE
boblight support for standalone player, native build script

### PR DESCRIPTION
**Pull request by Stasik0**
Copy of the previous request, now in a new branch, sorry for the stress.

### CODE REVIEW

**Comment by Stasik0** [comment]
The problem was, that the callback had to be a static function due to its generic type, and hence, everything that is called from it needed to be static as well... now the code structure has changed, right... i will fix it in the evening.

**Comment by huceke** [comment]
Look in OMXCore.cpp how to do callbacks the right way.

**Comment by Stasik0** [comment]
I use the previously added SetCustomDecoderFillBufferDoneHandler() in the core, did you mean that? Still the actual callback has to be static, otherwise the signatures do not match.

**Comment by Stasik0** [comment]
i moved the initialization to constructor, unfortunately, i have to use static functions for callbacks and pthread_create c.f. http://www.parashift.com/c++-faq/memfnptr-vs-fnptr.html

**Comment by Stasik0** [comment]
push

**Comment by regnets** [comment]
Is there a reason why this pull request is on hold?

**Comment by Stasik0** [comment]
up

**Comment by skgsergio** [comment]
Not part of the dev team but... IMO this feature should not be merged into omxplayer, the place for this feature is a fork with a maintainer who know the code and who knows if something has to be updated or changed.

**Comment by popcornmix** [comment]
Afraid I agree with @skgsergio.
Too invasive a change compared to the handful of people it benefits.
A fork is a better place for this.

**Pull request closed without merging**
