### PR TITLE
Apply volume to downmixing coefficients instead of audio_render

### PR DESCRIPTION
**Pull request by torarin**
See discussion at https://github.com/huceke/omxplayer/pull/55

### CODE REVIEW

**Comment by huceke** [comment]
@popcornmix did you add the needed changes to the upstream firmware ?

**Comment by popcornmix** [comment]
Yes, upstream firmware supports the new mixing coefficients.
The pull request looks good to me (and we should think about something similar for xbmc).

**Comment by huceke** [comment]
@popcornmix: if you are compftable with it, hit the green button :D

**Comment by popcornmix** [comment]
A few comments:
The normalise step, whilst ensuring clipping doesn't occur (for non-boosting volume) does make the audio quieter (except when every channel is identical). This suggests users will have to manually adjust volume for stereo and 5.1 sources to get the same perceived volume level. A "boost on downmix" option to compensate may still be relevant.
This just deals with 6, and 8 channel audio. It might be worth adding 2.1 and 5.0 inputs, for example.
You could use the downmixing_coefficients_8 array for the 6 channel case, as we always send 8 channels of audio, and the last two channels are zero.

But, the change looks good, thanks for the PR.

**Comment by torarin** [comment]
Yeah, I can see that a boost-on-downmix switch would be useful. I'd also like to add center-boost matrices. The reason for using a separate array for 6-channel was that it allows the normalizing logic to be agnostic about channel count.

**Pull request merged**
