### PR TITLE
OpenVG subtitles

### PR DESCRIPTION
**Pull request by torarin**
Renders subtitles using Freetype for glyph rendering and OpenVG for glyph caching and compositing. I've been conservative about adding new options, only font path and font size for now, otherwise I think the defaults are good.

I wish I could have timed the subtitles using OpenMAX media time requests, but unfortunately they don't seem to work when the clock is tunnelled to other components. Instead, I use a loop which sleeps for 16 ms when idle.

Does not parse italics yet.

### CODE REVIEW

**Comment by huceke** [comment]
Thank you for the effort. Please rework it a bit.

1.) Look at OMXPlayerVideo.cpp/OMXPlayerVideo.h and keep your code in the same style.

2.) Use OMXThread for the subtitle thread, to keep consistency for threading.

3.) It doesn't compile with g++ 4.7.0 :

In file included from enforce.h:3:0,
                 from SubtitleRenderer.cpp:20:
/media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/stdexcept:65:13: error: looser throw specifier for 'virtual std::logic_error::~logic_error()'
In file included from /media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/new:42:0,
                 from /media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/ext/new_allocator.h:34,
                 from /media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/arm-unknown-linux-gnueabi/bits/c++allocator.h:34,
                 from /media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/bits/allocator.h:48,
                 from /media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/vector:62,
                 from SubtitleRenderer.h:24,
                 from SubtitleRenderer.cpp:17:
/media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/exception:66:13: error:   overriding 'virtual std::exception::~exception() noexcept (true)'
In file included from enforce.h:3:0,
                 from SubtitleRenderer.cpp:20:
/media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/stdexcept:70:5: error: looser throw specifier for 'virtual const char\* std::logic_error::what() const'
In file included from /media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/new:42:0,
                 from /media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/ext/new_allocator.h:34,
                 from /media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/arm-unknown-linux-gnueabi/bits/c++allocator.h:34,
                 from /media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/bits/allocator.h:48,
                 from /media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/vector:62,
                 from SubtitleRenderer.h:24,
                 from SubtitleRenderer.cpp:17:
/media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/exception:70:25: error:   overriding 'virtual const char\* std::exception::what() const noexcept (true)'
In file included from enforce.h:3:0,
                 from SubtitleRenderer.cpp:20:
/media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/stdexcept:122:13: error: looser throw specifier for 'virtual std::runtime_error::~runtime_error()'
In file included from /media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/new:42:0,
                 from /media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/ext/new_allocator.h:34,
                 from /media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/arm-unknown-linux-gnueabi/bits/c++allocator.h:34,
                 from /media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/bits/allocator.h:48,
                 from /media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/vector:62,
                 from SubtitleRenderer.h:24,
                 from SubtitleRenderer.cpp:17:
/media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/exception:66:13: error:   overriding 'virtual std::exception::~exception() noexcept (true)'
In file included from enforce.h:3:0,
                 from SubtitleRenderer.cpp:20:
/media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/stdexcept:127:5: error: looser throw specifier for 'virtual const char\* std::runtime_error::what() const'
In file included from /media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/new:42:0,
                 from /media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/ext/new_allocator.h:34,
                 from /media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/arm-unknown-linux-gnueabi/bits/c++allocator.h:34,
                 from /media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/bits/allocator.h:48,
                 from /media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/vector:62,
                 from SubtitleRenderer.h:24,
                 from SubtitleRenderer.cpp:17:
/media/usbdisk/xbmc/xbmc-bcm/buildroot-rbp/output/host/usr/lib/gcc/arm-unknown-linux-gnueabi/4.7.0/../../../../arm-unknown-linux-gnueabi/include/c++/4.7.0/exception:70:25: error:   overriding 'virtual const char\* std::exception::what() const noexcept (true)'

A short google showed me, that throwing exeotions in a constructor/destructor is not a good idea. Try to avoid exeptions and use clean error handler and return values.

**Comment by torarin** [comment]
1.) I have indeed tried to keep OMXPlayerSubtitles in the same style as the other OXMPlayer*s. However, I took the liberty of considering SubtitleRenderer to be an external component (much like OpenVG) and thus used my own naming scheme and bracing style. If there are inconsistencies in OMXPlayerSubtitles I'll be happy to fix them.

2.) Please reconsider. As far as I can tell I have kept the interface and semantics the same, so I find it a bit disheartening to change implementation details when OMXThread is not actually used polymorphically.

3.) EDIT: I'm getting the same error on 4.7. Will investigate.

4.) Finally, could you point me to the destructor that can throw? I definitely want to correct that. I don't think it is problematic to throw from constructors, though.

**Comment by torarin** [comment]
gcc 4.7 will now compile it for me, let me know if you still get errors.

**Comment by huceke** [comment]
With your patch :

[New LWP 1350]

Program received signal SIGSEGV, Segmentation fault.
[Switching to LWP 1350]
0x40ee5530 in ?? () from /usr/lib/libstdc++.so.6
(gdb) thread apply all bt

Thread 2 (LWP 1350):
#0  0x40ee5530 in ?? () from /usr/lib/libstdc++.so.6
#1  0x40129e2c in ?? () from /lib/libpthread.so.0
#2  0x40129e2c in ?? () from /lib/libpthread.so.0
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (LWP 1340):
#0  0x4012ea54 in pthread_cond_signal () from /lib/libpthread.so.0
#1  0x400e08a8 in vcos_timer_set (timer=0x5c2a8, delay_ms=<optimized out>) at /home/dc4/raspberry/arm_linux/vc4/interface/vcos/pthreads/vcos_pthreads.c:775
#2  0x400cbeb0 in ilcs_execute_function_ex () from /opt/vc/lib/libopenmaxil.so
#3  0x400cc408 in ilcs_execute_function () from /opt/vc/lib/libopenmaxil.so
#4  0x400cd6e0 in vcil_out_create_component () from /opt/vc/lib/libopenmaxil.so
#5  0x400c26e8 in OMX_GetHandle () from /opt/vc/lib/libopenmaxil.so
#6  0x0002356c in COMXCoreComponent::Initialize (this=0x983e8, component_name=..., index=OMX_IndexParamAudioInit) at OMXCore.cpp:1264
#7  0x0002879c in COMXAudio::Initialize (this=0x94678, pCallback=<optimized out>, device=..., iChannels=<optimized out>, channelMap=0x7b98c, uiSamplesPerSec=48000, uiBitsPerSample=16, 
    bResample=false, bIsMusic=false, bPassthrough=IAudioRenderer::ENCODED_NONE) at OMXAudio.cpp:300
#8  0x0002e24c in OMXPlayerAudio::OpenDecoder (this=this@entry=0x44f90) at OMXPlayerAudio.cpp:625
#9  0x0002ec6c in OMXPlayerAudio::Open (this=0x44f90, hints=..., av_clock=<optimized out>, omx_reader=0x45510, device=..., passthrough=false, hw_decode=false, use_thread=true)
    at OMXPlayerAudio.cpp:150
#10 0x0000fae0 in main (argc=<optimized out>, argv=<optimized out>) at omxplayer.cpp:485

That is not good at all. Don't know what's the side effect using "-std=c++0x" has.

Another problem is "folly" it is under the Apache Licencse which is not compatible with the GPLv2 of omxplayer.

http://www.gnu.org/licenses/license-list.html#apache2

Let me know how to continue. In the current state i can't merge this.

**Comment by ph0ng** [comment]
Perhaps it won't make a difference, but I for one am really looking forward to this addition and hope that you solve the mentioned problems. In my opinion, omxplayer would be _the_ video player for RPI with proper subtitle rendering. 

I built your 'subtitles' branch on an up-to-date Arch Pi and got SIGILL from playing .mkv containers with embedded subtitles (non-subbed containers still work). GDB output: 

Program received signal SIGILL, Illegal instruction.
0x41c25e00 in _armv7_neon_probe () from /usr/lib/libcrypto.so.1.0.0

**Comment by torarin** [comment]
Thank you, ph0ng! At least I am able to reproduce the segfault by building it natively on Wheezy.

Regarding the incompatible licences, the omxplayer files say "either version 2 of the License, or (at your option) any later version". Since GPL v3 is compatible with Apache, it seems to me that this is allowed (at the very least if the permission to use version 2 is explicitly removed).

**Comment by torarin** [comment]
The native gcc 4.6 segfault appears to be an arm1176jzf-s codegen bug. Even the simplest std::thread test case segfaults with -mcpu=arm1176jzf-s:

```
#include <thread>

void foo() {}

int main() {
  std::thread t(foo);
  t.join();
  return 0;
}
```

Using native gcc 4.7.1 it does not segfault, but the error message is hardly comforting:

```
pure virtual method called
terminate called without an active exception
Aborted
```

It seems likely that this problem is related to huceke's segfault, so I decided to replace std::thread with OMXThread after all.

With this change, I can build and run this natively on Wheezy using both gcc 4.6 and 4.7.1, as well as with the official gcc 4.5 cross-compile toolchain.

Ph0ng's SIGILL originates from libcrypto, and is also mentioned at http://archlinuxarm.org/forum/viewtopic.php?f=31&t=3004&start=50#p18351 in conjunction with XBMC. Luckily, omxplayer doesn't require this library (or libssl, which may be what needed libcrypto), so you should be able build omxplayer without linking to it. 

Let me know how it goes.

**Comment by ph0ng** [comment]
"pure virtual method called" was what I got originally, the SIGILL (an armv7 instruction) was probably bogus data from gdb caused by the same error. 

With the latest commits I am able to play Matroska containers without crashing, but if subtitles are present omxplayer.bin instead reports 

> libEGL warning: DRI2: xcb_connect failed
> libEGL warning: DRI2: xcb_connect failed
> libEGL warning: GLX: XOpenDisplay failed

Will experiment more later this evening or tomorrow, perhaps we have a new dependency?

**Comment by huceke** [comment]
You are using the wrong EGL library. 

Check if you have /usr/lib libEGL.so. 

The PI one is /opt/vc/lib/libEGL.so.

**Comment by ph0ng** [comment]
Indeed, huceke. My binary was referencing both paths, and I had to replace the -lEGL LDFLAG with -L/opt/vc/lib for it to work. 

@torarin Now I can see beautiful (though not centered) text for Matroska files. However, when playing an .mp4 together with .srt there is no text and I get this when pressing the 'm' key (same goes for non-subbed Matroska files): 

> omxplayer.bin: OMXPlayerSubtitles.cpp:144: void OMXPlayerSubtitles::Flush(): Assertion `m_open' failed

Additionally, the default FreeSans font path in Arch is /usr/share/fonts/TTF/FreeSans.ttf. This is not a big problem for me but perhaps the program could try this if the first path is invalid.

**Comment by torarin** [comment]
Oh, you like them centered? I find it beneficial to give the eyes a fixed horizontal starting position for reading a line of text. It's also what I'm used to from Scandinavian television. Obviously highly subjective, so it should be selectable at some point.

Good catch on the assertion error! It does not read subtitle files like srt yet, you'll have to mux it in. Also, you may find 'm' and 'n' somewhat impractical. It currently keeps track of only one subtitle stream at the time, which means that it takes a while for the video to catch up with the stream switch.

Regarding fonts, I think a good solution is to have packages provide an appropriate font path in the omxplayer shell script.

**Comment by ph0ng** [comment]
Yes, the television shows use left-justified subtitles (I am from Sweden myself), though I believe theaters use centered text for feature films. Not a big deal at the moment. As you suggest, using package specific shell scripts is a clean solution. 

A bit off-topic: I am experiencing some video/audio lag in various scenes with your branch and it gets even worse after installing the latest x264/ffmpeg versions. Am I correct in my assumption that this should have no impact since ffmpeg is supposed to be built together with omxplayer? Most probably, I broke something while editing the makefiles... I am leaving for vacation for a few days, perhaps the merge is complete when I get back so I can use the real omxplayer PKGBUILD :)

**Comment by torarin** [comment]
Yes, centered text at theaters here as well. I believe the rationale is that it should be equally readable whether you sit on the far left or far right.

It isn't all that surprising if something breaks when you use the wrong ffmpeg version, but it would be interesting to hear if you get the same behavior with huceke's branch.

**Comment by ph0ng** [comment]
Another benefit is that the eyes are focused on the center of the picture most of the time and thus centered text minimizes effective eye movement distance. This in turn can reduce some nasty rainbow effects found on projectors and plasma displays. 

I am heading out now and will not have time to test this on the main branch for some days. I still think that the issue is caused by me not building the ffmpeg target.

**Comment by ph0ng** [comment]
OK, it seems like the movies I am playing are pushing the limits of the hardware. I tested yet another movie (1080p, DTS audio), which was lagging even without this patch. Then I discovered that everything played smoothly once I set the audio passthrough flag. This applies for a variety of movies, both with DTS and AC3 and with subtitles enabled. Interestingly enough, some movies do play fine without subtitles meaning that the computational overhead is not insignificant. 

This is becoming a bit off-topic, but is there anything I can do to improve audio performance? My TV does not seem to be able to decode DTS (I assume that this is what passthrough is for). The next step might be to re-encode the streams to stereo AAC which is good enough for me. 

**UPDATE:** After transcoding to stereo audio, it's fine. Still I think centered text (as well as fully transparent background, custom colors, italics, .srt support etc) would be nice, perhaps I can try to fix that myself :)

**UPDATE 2:** The 's' key does not toggle subtitles (bool m_show_subtitle is set but never used).

**Comment by torarin** [comment]
Checking the time every 16 ms is quite expensive. OpenMAX media time requests would be much cheaper, but I can't make them work properly at the moment. It might be a good idea to turn RENDER_LOOP_SLEEP in OMXPlayerSubtitles.cpp up a notch. Since I haven't had any problems with software audio decoding, it is set quite low.

The software decoders will probably be more capable if you use a hard-float distribution like Raspbian.

You'll definitely get the things you want, I just hope to get the basic thing approved first. Box opacity and white level are arguments to SubtitleRenderer, so those are pretty straightforward to adjust.

I'll look into the toggle subtitles bug.

**Comment by ph0ng** [comment]
Setting RENDER_LOOP_SLEEP to 100 gives me smooth playback of the files tested so far (a value of 64 still showed symptoms). I understand that we lose some precision, but it may be worth it to maintain playback performance.

**Comment by ph0ng** [comment]
Works well, although OSD info when toggling subtitles would be even nicer ;-)

**Comment by torarin** [comment]
Sure. Someday ;-)

**Comment by torarin** [comment]
@huceke, have you had a chance to look at the latest changes? Is there anything you need me to do?

**Comment by huceke** [comment]
Had look at it. My concern is still the Apache vs. GPL2 licence issue. omxplayer is under the GPL v2 and not GPL v3.

**Comment by torarin** [comment]
I understand, I will try to explain my reasoning. This is the relevant part of the licence blurb in omxplayer.cpp:

```
This Program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.
```

In other words, I can redistribute and modify omxplayer under GPL version >= 2. Accordingly, I pick version 3 and combine it with Apache Licence 2 code, as is allowed per http://www.gnu.org/licenses/license-list.html#apache2 .

The question is, is it still allowed to say "either version 2" despite being implicitly bounded by version 3? I'm not sure, so if you are worried about that, I propose changing the notices to instead say "either version 3" (such a change is expressly permitted by the above notice).

You may, of course, have good reason to keep allowing _redistribution_ under GPL v2, in which case I will rework my code to not use folly. But if that is not an issue, I believe we are in the clear.

**Comment by huceke** [comment]
You are not allowed to change from v2 to v3 without the permission of the copyright holder. In our case, the holders are the XBMC Team. and me  To have the posability to share code between XBMC and omxplayer i'll not going to change the licence.

**Comment by torarin** [comment]
Clearly, I _am_ allowed to change from v2 to v3 because the copyright holder has indeed given me permission to do so. I repeat the quote from the license notice: "either version 2, or (at your option) any later version". I.e. at my option, I may use v3. I don't understand what you mean, are the omxplayer license notices somehow incorrect?

Now, if you did bump the omxplayer GPL version up to >= 3, people would not, in general, be able to merge omxplayer code into XBMC (but anyone could still merge XBMC code into omxplayer - the XBMC licence is _compatible with_ GPL v3).

However, you and Team XBMC hold copyrights to contributions to omxplayer (the files say either "Copyright (C) xxxx-xxxx Team XBMC" or "Copyright (C) 2012 Edgar Hucek". My new subtitle files don't, but I hereby give you permission to do anything you want with them), and thus you may relicense omxplayer code into GPL v2 for inclusion in XBMC as needed.

If you still don't agree, I will stop arguing now.

**Comment by huceke** [comment]
I do not agree with you. So lets move to your offer to remove folly. Users will love you for the subtitles ;)

**Comment by torarin** [comment]
I have opened a new pull request for this.

**Pull request closed without merging**
