### PR TITLE
External subtitles

### PR DESCRIPTION
**Pull request by torarin**
This implements support for external srt subtitle files.

Additionally, switching of subtitle streams during playback is now responsive, subtitle delay is adjustable using "d" and "f", and all file paths are confirmed to exist before trying to open them.

The added files are all rather trivial, except for utils/variant.hpp, utils/variant-impl.hpp and utils/traits.hpp. They are Boost-licensed and come from from https://github.com/kennytm/utils. It's a rewrite of boost::variant with proper C++11 move semantics.

### CODE REVIEW

**Comment by huceke** [comment]
My buildroot env uses boost 1.49.0. So it doesn't compile :

OMXPlayerSubtitles.cpp:27:37: fatal error: boost/algorithm/clamp.hpp: No such file or directory
compilation terminated.

Updating boost on my buildroot env is no option. I dislike it to bring in more boost dependencies.

**Comment by torarin** [comment]
Of course, sorry. Are you okay with linking to libboost_regex?

**Comment by huceke** [comment]
I would appreciate when we can avoid it.

**Comment by gabbello** [comment]
Thank you for your hard work on this, I would love to have external subtitle support in omxplayer. Any plans to have this merged? I tried building omxplayer from torarin repo, but I get errors while makeing ffmpeg.

**Comment by torarin** [comment]
This patch no longer merges smoothly, so I'll try to find time to resolve that soon.

You could try to skip building ffmpeg and link directly to the libraries that come with skgsergio's binary packages.

**Comment by gabbello** [comment]
Thank you, I will try your suggestion regarding ffmpeg.

**Comment by gabbello** [comment]
Torarin, thanks for the experimental deb package with subtitle support. I downloaded it from your github page and it works great so far

**Comment by gabbello** [comment]
I'm getting:
 00:00:00 T:0   ERROR: OMXPlayerSubtitles::RenderLoop threw 13Enforce_error (Enforcement failed in SubtitleRenderer.cpp(477))

on various videos/subs (and the subs are not showing). Any idea what this might be?

**Comment by torarin** [comment]
In all likelyhood a GPU out-of-memory error. Are you using the latest deb? https://github.com/downloads/torarin/omxplayer/omxplayer_2~experimental~git20121026~3dd2bc29_armhf.deb It is more memory efficient with regard to subtitles.

**Comment by gabbello** [comment]
yes, I just downloaded the latest one and still the same behaviour

**Comment by torarin** [comment]
Did you do a reboot? What memory split are you using? Could you upload a small video/sub combination that fails? Did the line referred to in the log error message change?

**Comment by gabbello** [comment]
I'm using a 192 - 64 default split. I just double checked this (using free I see that I have 192 RAM) since I know the latest versions changed the way RAM is handled (allowing to specify the RAM allocated for GPU). Is there a command to see the video ram usage (like free for RAM)? 

I tried a reboot, but the error message is always the same. 

I tried using a 128-128 RAM split and now the subtitles work, so indeed there is a memory issue, but not sure how it was working before. Unfortunately I don't have the files that I know for sure that worked to double check those ones.

**Comment by torarin** [comment]
It is possible the memory requirements for certain codecs have changed in recent firmware.

You can try running `sudo /opt/vc/bin/vcdbg reloc` and look for large allocations.

The main subtitle-related allocations look like this:

```
[  79] 0xa4d7e40: used  160 (refcount 2 lock count 0, size    116, d0rua) 'EGL_SERVER_SURFACE_T'
[  76] 0xa4d7ee0: used 1.8M (refcount 1 lock count 0, size 1858560, d1Rua) 'KHRN_IMAGE_T.storage'
[  75] 0xa69eae0: used 1.8M (refcount 1 lock count 0, size 1858560, d1Rua) 'KHRN_IMAGE_T.storage'
[  77] 0xa8656e0: used 1.8M (refcount 1 lock count 0, size 1858560, d1Rua) 'KHRN_IMAGE_T.storage'
```

You can reduce subtitle memory usage further by setting `-lines 2`. According to @popcornmix, it should also be possible to switch from triple to double buffering by setting the environment variable V3D_DOUBLE_BUFFER equal to 1. However, vcdbg still reports three KHRN_IMAGE_T.storage allocations.

**Comment by gabbello** [comment]
Thanks, for now I set a non standard RAM split and gave gpu 80 MB. It is a bit strange that when loading the same movie with subtitles that did not worked before now I have:

Relocatable heap version 4 found at 0xc380000
total space allocated is 60M, with 58M relocatable, 2.3M legacy and 0 offline
1 legacy blocks of size 2359296

free list at 0xceb3dc0
43M free memory in 6 free block(s)
largest free block is 28M bytes

so, in theory 64 should have also been enough.

Indeed setting the V3D_DOUBLE_BUFFER env. variable doesn't seem to help

**Comment by rycus86** [comment]
Hi!

I'm trying to compile torarin's version (the experimental branch). ffmpeg compiled fine but I'm having trouble compiling OMXPlayerSubtitles.cpp. Here is the relevant log from make: http://pastebin.com/ZAH9EzvF
Could you please help me? I think I'm using a wrong version of some libs.

Thanks in advance!

**Comment by torarin** [comment]
Oh my, what a horrible error message! The first error gives it away, though. You need to use GCC 4.7.

**Comment by rycus86** [comment]
Argh... Thank you so much! I've installed GCC 4.7 just didn't update the symbolic link for it...

**Comment by Stasik0** [comment]
Any updates on the srt support?

**Comment by popcornmix** [comment]
@torarin 
Can you resubmit this pull request? 
(Ideally with memory reduced overlay)

**Comment by zegman** [comment]
I am getting the following using the latest build (omxplayer_3~experimental~git20121208~ebfa6fc6_armhf.deb):
00:00:00 T:0   DEBUG: DllOMX: Using omx system library
00:00:00 T:0   DEBUG: COMXCoreComponent::Initialize OMX.broadcom.audio_mixer inp
ut port 232 output port 231
00:00:00 T:0   DEBUG: COMXCoreComponent::AllocInputBuffers component(OMX.broadco
m.audio_decode) - port(120), nBufferCountMin(4), nBufferCountActual(57), nBuffer
Size(6144), nBufferAlignmen(16)
00:00:00 T:0   ERROR: OMXPlayerSubtitles::RenderLoop threw 13Enforce_error (Enforcement failed in SubtitleRenderer.cpp(477))
00:00:00 T:0   DEBUG: OMXThread::Run - Exited thread with  id 1172816992
00:00:00 T:0   DEBUG: COMXAudio::Initialize Ouput bps 16 samplerate 44100 channels 2 device hdmi buffer size 352800 bytes per second 176400 passthrough 0 hwdecode 0

**Comment by torarin** [comment]
@zegman, it's a GPU memory issue. See the above discussion.

**Comment by zegman** [comment]
Yes, I've read it.
I am not sure its the same issue though.
I am getting it with .avi files.
Will increasing the GPU memory solve this?
How do you do that?

**Comment by popcornmix** [comment]
Try gpu_mem=128 in /boot/config.txt (and reboot).

**Comment by zegman** [comment]
Thanks, it works!

**Pull request closed without merging**
