### PR TITLE
automatically choose audio path

### PR DESCRIPTION
**Pull request by ghost**
This is just a small patch to the omxplayer script, it uses use /opt/vc/bin/tvservice -s to find out if HDMI is being used, and if so adds "--adev hdmi" to the list of parameters.

I figured it would prevent most users needing to edit their omxplayer script (but I think those using HDMI-DVI converters would still need to)

### CODE REVIEW

**Comment by popcornmix** [comment]
Using:
tvservice -a
     PCM supported: Max channels: 2, Max samplerate:  48kHz, Max samplesize 24 bits.
     AC3 supported: Max channels: 6, Max samplerate:  48kHz, Max rate  640 kb/s.
will distinguish HDMI with audio support from HDMI without audio (e.g. DVI).

It's a reasonable request, and may be better implemented in the omxplayer binary.
(i.e. still support -o hdmi and -o local, but if unspecified it tries to detect).

I'll look into it.

**Comment by KenT2** [comment]
Seems like a useful addition however please allow any automatic choice to be overridden if -o is specified as suggest by popcornmix. In embedded applications hdmi sound will not always be used even with a hdmi tele and its impractical to expect users to edit the omxplayer script.

**Comment by popcornmix** [comment]
@archiebawled @KenT2 
Please test https://github.com/huceke/omxplayer/commit/b4922b97458d6df292faba8a64dcf0db6dd0bf73
and let me know it does what you want.

**Comment by KenT2** [comment]
The 'do auto if option not specified' bit looks fine.
Thanks
Ken

**Comment by popcornmix** [comment]
This is implemented.

**Pull request closed without merging**
